In [2]:
import sys
sys.path.append('d:/code/pywfn')
from pywfn.base import Mol
from pywfn.reader import LogReader
from pywfn.atomprop import charge
import numpy as np

动态链接库目录 d:\code\pywfn\pywfn\libs
当前系统:windows


In [3]:
root='D:/gfile/pywfn/pi电子/没有D'
# root='D:/gfile/pywfn/pi电子'
names=['CH2CHCl.log','CO2.log','NO3.log','CO3.log','BF3.log','Ph2.log','NO2.log','CH2CHCH2+.log','CH2CHCHO.log','NNO.log']
paths=[f'{root}/{name}' for name in names]
mols=[Mol(LogReader(path)) for path in paths]

In [21]:
mol=mols[0]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

CH2CHCl.log


(array([[1.    , 0.    , 0.    , 1.    , 1.0106],
        [2.    , 0.    , 0.    , 1.    , 0.    ],
        [3.    , 0.    , 0.    , 1.    , 0.    ],
        [4.    , 0.    , 0.    , 1.    , 1.0809],
        [5.    , 0.    , 0.    , 1.    , 0.    ],
        [6.    , 0.    , 0.    , 1.    , 2.0731]]),
 np.float64(4.164575285586991))

In [22]:
mol=mols[1]
for i in range(3):
    mol.atom(i+1)._props['normal']=np.array([0,1,0],dtype=float)
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

CO2.log


(array([[1.    , 0.    , 1.    , 0.    , 0.8382],
        [2.    , 0.    , 1.    , 0.    , 1.5809],
        [3.    , 0.    , 1.    , 0.    , 1.5809]]),
 np.float64(4.000003363896836))

In [23]:
mol=mols[2]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

NO3.log


(array([[1.    , 0.    , 0.    , 1.    , 1.1547],
        [2.    , 0.    , 0.    , 1.    , 1.5564],
        [3.    , 0.    , 0.    , 1.    , 1.5564],
        [4.    , 0.    , 0.    , 1.    , 1.5564]]),
 np.float64(5.8238702777698705))

In [24]:
mol=mols[3]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

CO3.log


(array([[ 1.    , -0.    ,  0.    ,  1.    ,  0.7937],
        [ 2.    , -0.    ,  0.    ,  1.    ,  1.7069],
        [ 3.    , -0.    ,  0.    ,  1.    ,  1.7069],
        [ 4.    , -0.    ,  0.    ,  1.    ,  1.7069]]),
 np.float64(5.9142892729759975))

In [25]:
mol=mols[4]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

BF3.log


(array([[ 1.    , -0.    , -0.    ,  1.    ,  0.4176],
        [ 2.    , -0.    , -0.    ,  1.    ,  1.8608],
        [ 3.    , -0.    , -0.    ,  1.    ,  1.8608],
        [ 4.    , -0.    , -0.    ,  1.    ,  1.8608]]),
 np.float64(6.000042409789458))

In [26]:
mol=mols[5]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

Ph2.log


(array([[ 1.    ,  1.    ,  0.    ,  0.    ,  1.0059],
        [ 2.    , -1.    ,  0.    ,  0.    ,  1.0081],
        [ 3.    ,  1.    ,  0.    ,  0.    ,  0.9718],
        [ 4.    , -1.    ,  0.    ,  0.    ,  0.9718],
        [ 5.    ,  1.    , -0.    ,  0.    ,  1.0081],
        [ 6.    , -1.    ,  0.    , -0.    ,  1.0059],
        [ 7.    , -1.    ,  0.    ,  0.    ,  0.    ],
        [ 8.    ,  1.    ,  0.    ,  0.    ,  0.    ],
        [ 9.    , -1.    ,  0.    ,  0.    ,  0.    ],
        [10.    , -1.    ,  0.    ,  0.    ,  1.0081],
        [11.    ,  1.    , -0.    ,  0.    ,  1.0081],
        [12.    ,  1.    , -0.    ,  0.    ,  0.    ],
        [13.    , -1.    ,  0.    , -0.    ,  0.    ],
        [14.    ,  1.    , -0.    ,  0.    ,  1.0059],
        [15.    ,  1.    ,  0.    ,  0.    ,  1.0059],
        [16.    ,  1.    , -0.    ,  0.    ,  0.    ],
        [17.    ,  1.    , -0.    ,  0.    ,  0.    ],
        [18.    ,  1.    ,  0.    ,  0.    ,  0.    ]]),
 np.floa

In [27]:
mol=mols[6]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

NO2.log


(array([[ 1.    , -1.    ,  0.    ,  0.    ,  1.0485],
        [ 2.    , -1.    ,  0.    ,  0.    ,  1.4758],
        [ 3.    , -1.    ,  0.    ,  0.    ,  1.4758]]),
 np.float64(4.000044161076342))

In [4]:
mol=mols[7]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

CH2CHCH2+.log


(array([[ 1.    , -0.    , -0.    ,  1.    ,  0.5268],
        [ 2.    , -0.    , -0.    ,  1.    ,  0.    ],
        [ 3.    , -0.    , -0.    ,  1.    ,  0.    ],
        [ 4.    , -0.    , -0.    ,  1.    ,  0.9462],
        [ 5.    , -0.    , -0.    ,  1.    ,  0.    ],
        [ 6.    , -0.    , -0.    ,  1.    ,  0.527 ],
        [ 7.    , -0.    , -0.    ,  1.    ,  0.    ],
        [ 8.    , -0.    , -0.    ,  1.    ,  0.    ]]),
 np.float64(2.000016644523757))

In [6]:
mol=mols[8]
print(mol.reader.fname)
caler=charge.Calculator(mol)
vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

CH2CHCHO.log


(array([[ 1.    , -0.    , -0.    ,  1.    ,  0.9301],
        [ 2.    , -0.    , -0.    ,  1.    ,  0.    ],
        [ 3.    , -0.    , -0.    ,  1.    ,  0.    ],
        [ 4.    , -0.    , -0.    ,  1.    ,  0.9784],
        [ 5.    , -0.    , -0.    ,  1.    ,  0.    ],
        [ 6.    ,  0.    ,  0.    ,  1.    ,  0.8107],
        [ 7.    ,  0.    ,  0.    ,  1.    ,  0.    ],
        [ 8.    ,  0.    ,  0.    ,  1.    ,  1.2808]]),
 np.float64(4.000019120749458))

In [8]:
mol=mols[9]
print(mol.reader.fname)
for i in range(3):
    mol.atom(i+1)._props['normal']=np.array([0,0,1],dtype=float)
caler=charge.Calculator(mol)

vals=caler.piElectron('mulliken')
vals,np.sum(vals[:,-1])

NNO.log


(array([[1.    , 0.    , 0.    , 1.    , 1.2607],
        [2.    , 0.    , 0.    , 1.    , 1.0905],
        [3.    , 0.    , 0.    , 1.    , 1.6488]]),
 np.float64(4.000005974256763))