In [2]:
import sys
sys.path.append('d:/code/pywfn')
from pywfn.base import Mol
from pywfn.reader import LogReader
from pywfn.atomprop import charge
import numpy as np

动态链接库目录 d:\code\pywfn\pywfn\libs
当前系统:windows


In [3]:
root='D:/gfile/HFV/lu活性'
# root='D:/gfile/pywfn/pi电子'
names=['A3','A4','A6']
paths_0=[f'{root}/{name}.log' for name in names]
paths_n=[f'{root}/{name}_n.log' for name in names]
paths_p=[f'{root}/{name}_p.log' for name in names]
mols0=[Mol(LogReader(path)) for path in paths_0]
molsn=[Mol(LogReader(path)) for path in paths_n]
molsp=[Mol(LogReader(path)) for path in paths_p]

In [9]:
iatm=0
mol0=mols0[iatm]
moln=molsn[iatm]
molp=molsp[iatm]
vals0=charge.Calculator(mol0).piElectron('mulliken')
valsn=charge.Calculator(moln).piElectron('mulliken')
valsp=charge.Calculator(molp).piElectron('mulliken')
reasn=vals0[:,-1]-valsp[:,-1]
reasp=valsn[:,-1]-vals0[:,-1]
reasd=reasp-reasn
resList=[]
atms=vals0[:,0]
print(valsn)
print(vals0)
print(valsp)
for i,atm in enumerate(atms):
    atom=mol0.atom(int(atm))
    resList.append((atom.idx,reasd[i].item()))
resList.sort(key=lambda x:x[1],reverse=True)
print('--双描述符(pi)--')
for each in resList:
    atm=each[0]
    if mol0.atom(atm).symbol!='C':continue
    print(each)

vals0=charge.Calculator(mol0).charge('mulliken')
valsn=charge.Calculator(moln).charge('mulliken')
valsp=charge.Calculator(molp).charge('mulliken')
reasn=valsp-vals0
reasp=vals0-valsn
reasd=reasp-reasn
resList=[]
for i,atom in enumerate(mol0.atoms):
    resList.append((atom.idx,reasd[i].item()))
resList.sort(key=lambda x:x[1],reverse=True)
print('--双描述符--')
for each in resList:
    atm=each[0]
    if mol0.atom(atm).symbol!='C':continue
    print(each)

[[ 1.      0.      0.      1.      1.0237]
 [ 2.     -0.      0.      1.      1.0364]
 [ 3.     -0.      0.      1.      1.1609]
 [ 4.      0.      0.      1.      1.0364]
 [ 5.      0.      0.      1.      1.0237]
 [ 6.      0.      0.      1.      1.0616]
 [ 7.      0.      0.      1.      0.    ]
 [ 8.      0.      0.      1.      0.    ]
 [ 9.      0.      0.      1.      0.    ]
 [10.     -0.      0.      1.      2.0972]
 [11.     -0.     -0.      1.      1.2701]
 [12.     -0.     -0.      1.      1.5811]
 [13.     -0.     -0.      1.      1.5811]
 [14.     -0.      0.      1.      0.    ]]
[[ 1.     -0.     -0.      1.      0.9692]
 [ 2.      0.     -0.      1.      0.9684]
 [ 3.      0.     -0.      1.      0.9912]
 [ 4.     -0.     -0.      1.      0.9729]
 [ 5.     -0.     -0.      1.      0.9519]
 [ 6.     -0.     -0.      1.      1.018 ]
 [ 7.     -0.     -0.      1.      0.    ]
 [ 8.     -0.     -0.      1.      0.    ]
 [ 9.     -0.     -0.      1.      0.    ]
 [10.     

In [12]:
mol0=mols0[iatm]
moln=molsn[iatm]
molp=molsp[iatm]
print(mol0)
vals0=charge.Calculator(mol0).charge('mulliken')
valsn=charge.Calculator(moln).charge('mulliken')
valsp=charge.Calculator(molp).charge('mulliken')
reasn=valsp-vals0
reasp=vals0-valsn
reasd=reasp-reasn
resList=[]
for i,atom in enumerate(mol0.atoms):
    resList.append((atom.idx,reasd[i].item()))
resList.sort(key=lambda x:x[1],reverse=True)
resList

<C6H3Cl2O2N1,14,96,0,1>


[(13, 0.37146364576057245),
 (14, 0.32931316622856777),
 (3, 0.033685174425004405),
 (1, 0.032322285919044624),
 (5, 0.024066081556465058),
 (8, 0.01635991709963025),
 (4, -0.001063373982926663),
 (6, -0.007868598818927097),
 (9, -0.014036842468115207),
 (2, -0.01966105388199768),
 (7, -0.042210598146586564),
 (10, -0.10769034732788896),
 (11, -0.1413022589587598),
 (12, -0.4043819622695972)]

In [15]:
vals0,valsn,valsp

(array([-0.1284, -0.1426, -0.0538, -0.1431, -0.1128,  0.2672,  0.1728,
         0.179 ,  0.1929,  0.0103,  0.254 , -0.1525, -0.2899,  0.176 ]),
 array([-0.1376, -0.1547, -0.0726, -0.1548, -0.127 ,  0.2881,  0.1173,
         0.1083,  0.134 , -0.1087,  0.1357, -0.5642, -0.5718,  0.1079]),
 array([-0.0894, -0.1093, -0.0417, -0.1149, -0.074 ,  0.2898,  0.2468,
         0.2489,  0.2522,  0.26  ,  0.2375, -0.1708, -0.1833,  0.2482]))

In [20]:
mol0.coords

array([[ 0.7072,  2.3887, -0.5315],
       [-1.9264,  2.2964, -0.4531],
       [-3.1343, -0.0078, -0.0052],
       [-1.7296, -2.2157,  0.3637],
       [ 0.9024, -2.126 ,  0.2813],
       [ 2.1034,  0.1818, -0.1615],
       [ 1.6588,  4.1596, -0.8739],
       [-2.6757, -3.9878,  0.7109],
       [ 2.003 , -3.8173,  0.5624],
       [-6.4458, -0.1327,  0.0955],
       [ 4.886 ,  0.2887, -0.2308],
       [ 5.9684,  1.1777,  1.8142],
       [ 6.016 , -1.5797, -1.3932],
       [-3.021 ,  3.9928, -0.7365]])

In [19]:
moln.coords

array([[ 0.7072,  2.3887, -0.5315],
       [-1.9264,  2.2964, -0.4531],
       [-3.1343, -0.0078, -0.0052],
       [-1.7296, -2.2157,  0.3637],
       [ 0.9024, -2.126 ,  0.2813],
       [ 2.1034,  0.1818, -0.1615],
       [ 1.6588,  4.1596, -0.8739],
       [-2.6757, -3.9878,  0.7109],
       [ 2.003 , -3.8173,  0.5624],
       [-6.4458, -0.1327,  0.0955],
       [ 4.886 ,  0.2887, -0.2308],
       [ 5.9684,  1.1777,  1.8142],
       [ 6.016 , -1.5797, -1.3932],
       [-3.021 ,  3.9928, -0.7365]])

In [21]:
charge.Calculator(mol0).hirshfeld()

array([-0.0549,  0.0534,  0.0691,  0.075 ,  0.1407, -0.0234,  0.0627,
        0.0901,  0.1366,  0.0824, -0.2675, -0.2706])

In [22]:
charge.Calculator(moln).mulliken()

array([-0.501 ,  0.1011,  0.1007,  0.0875,  0.3521, -0.3493,  0.0691,
        0.0348,  0.1471,  0.035 , -0.5601, -0.5168])

In [13]:
data=np.load('sn2_reactions.npz')

In [16]:
data.files

['R', 'Q', 'D', 'E', 'F', 'Z', 'N']

In [19]:
data['R'][0]

array([[ 0.0008,  0.0009, -5.3912],
       [ 0.0018,  1.0295, -5.0417],
       [-0.889 , -0.5126, -5.042 ],
       [ 0.8917, -0.5138, -5.042 ],
       [ 0.0005, -0.0009, -6.7826],
       [-0.0003, -0.    ,  2.0475]])

In [21]:
data['Q'].shape

(452709,)

In [26]:
data['Z'][2]

array([ 6,  1,  1,  1, 35,  9])