In [1]:
import numpy as np
import pyvista as pv
from pyvista.plotting.plotter import Plotter
import matplotlib.pyplot as plt
import matplotlib as mpl
import sys
sys.path.append(rf"D:\code\pywfn")
from pywfn.base import Mol
from pywfn.reader import LogReader
from pywfn.atomprop import activity,direction
from pywfn.bondprop import piDM
from pywfn.maths import points_rotate
import matplotlib.pyplot as plt
import matplotlib as mpl
from pathlib import Path
from pywfn.utils import printer
printer.ifShell=False
from collections import defaultdict

动态链接库目录 D:\code\pywfn\pywfn\libs
当前系统:windows


In [2]:
root=rf'D:\BaiduSyncdisk\Articles\HFV\gfile\M4\M4_wfn'
# root=r'D:\BaiduSyncdisk\Articles\HFV\gfile\NHC\NHC-wfn'
mn=Mol(LogReader(f'{root}-.log'))
m0=Mol(LogReader(f'{root}0.log'))
mp=Mol(LogReader(f'{root}+.log'))

## 计算自由价

In [3]:
results=defaultdict(list)
for m,mol in enumerate([mn,m0,mp]):
    valCaler=activity.Calculator(mol)
    dirCaler=direction.Calculator(mol)
    for atm in [3,25,26,27]:
        dirs=dirCaler.reactions(atm)
        result=valCaler.freeValence(atm,dirs)
        results[atm].append(result)

[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]
[[-2.6393 -0.469  -3.2388]]


In [4]:
atms=list(results.keys())
for atm in atms:
    vals=results[atm][1][:,-1]
    idx=np.argmax(vals)
    print(atm,idx,np.max(vals))

3 0 1.1719985063448644
25 13 1.0928647426143943
26 53 1.2773290423002641
27 0 1.027941729494378


In [5]:
results[26][1].shape

(57, 5)

In [7]:
for _,x,y,z,v in results[27][1]:
    print(f'[{x:>8.4f},{y:>8.4f},{z:>8.4f},{v:>8.4f}],')

[  0.1156,  0.5738,  0.8108,  1.0279],
[ -0.1156, -0.5738, -0.8108,  1.0279],


In [20]:
atms=list(results.keys())
for i in range(4):
    atm=atms[i]
    vns=results[atm][0][:,-1]
    v0s=results[atm][1][:,-1]
    vps=results[atm][2][:,-1]
    vn=np.max(vns)
    v0=np.max(v0s)
    vp=np.max(vps)
    mn=np.max(vns-v0s)
    mp=np.max(vps-v0s)
    print(f'{atm:>3},{vn:>10.4f},{v0:>10.4f},{vp:>10.4f},{mn:>10.4f},{mp:>10.4f}')

  3,    1.4664,    1.1720,    1.5080,    0.2944,    0.3360
 25,    1.2494,    1.0929,    1.2537,    0.1769,    0.1812
 26,    1.4489,    1.2742,    1.4406,    0.1772,    0.1667
 27,    1.1652,    1.0279,    1.1613,    0.1373,    0.1333


In [32]:
results[atms[2]][1]=results[atms[2]][1][19:,:]

In [36]:

atms=list(results.keys())
maxs={atm:0 for atm in atms}
idx=0
for atm in atms:
    for i,(a,x,y,z,v) in enumerate(results[atm][1]):
        print(f'[{a:.0f},{x:>6.2f},{y:>6.2f},{z:>6.2f},{v:>6.3f}],')
        idx+=1
        if v>maxs[atm]:maxs[atm]=idx

[3,  0.30,  0.48,  0.83, 1.172],
[3, -0.30, -0.48, -0.83, 1.172],
[25,  0.00, -0.04,  1.00, 1.082],
[25,  0.08,  0.12,  0.99, 1.079],
[25,  0.16,  0.28,  0.95, 1.075],
[25,  0.23,  0.43,  0.87, 1.073],
[25,  0.30,  0.56,  0.77, 1.073],
[25,  0.35,  0.68,  0.65, 1.073],
[25,  0.40,  0.77,  0.50, 1.075],
[25,  0.43,  0.84,  0.34, 1.078],
[25,  0.45,  0.88,  0.17, 1.082],
[25,  0.45,  0.89, -0.01, 1.085],
[25,  0.44,  0.88, -0.19, 1.088],
[25,  0.41,  0.83, -0.36, 1.091],
[25,  0.38,  0.76, -0.52, 1.092],
[25,  0.33,  0.67, -0.67, 1.093],
[25,  0.27,  0.55, -0.79, 1.092],
[25,  0.20,  0.42, -0.89, 1.091],
[25,  0.12,  0.27, -0.95, 1.088],
[25,  0.04,  0.12, -0.99, 1.084],
[25, -0.04, -0.04, -1.00, 1.081],
[25, -0.12, -0.20, -0.97, 1.077],
[25, -0.20, -0.35, -0.91, 1.074],
[25, -0.27, -0.50, -0.83, 1.073],
[25, -0.33, -0.62, -0.71, 1.073],
[25, -0.38, -0.72, -0.58, 1.074],
[25, -0.41, -0.81, -0.42, 1.077],
[25, -0.44, -0.86, -0.25, 1.080],
[25, -0.45, -0.89, -0.08, 1.083],
[25, -0.45, -0.8

## 计算双描述符

In [14]:
from pywfn.atomprop import activity,direction
mols:list[Mol]=[mn,m0,mp]
atms=[3,25,26,27]
for mol in mols:
    dirCaler=direction.Calculator(mol)
    mol.atom(25)._props['normal']=dirCaler.normal(3)
    mol.atom(26)._props['normal']=dirCaler.normal(27)
caler=activity.Calculator(m0)
res=caler.dual(mn,mp,chrg='mulliken')
for i,val in enumerate(res):
    if i+1 not in atms:continue
    print(f'{i+1:>3}{val:>10.4f}')

  3   -0.0296
 25   -0.0227
 26   -0.0645
 27   -0.0039


In [17]:
for atm,val in caler.dual_pi(mn,mp):
    if atm not in atms:continue
    print(f'{int(atm):>3}{val:>10.4f}')

  3   -0.0196
 25   -0.0467
 26   -0.0755
 27   -0.0421


In [3]:
from pywfn.atomprop import charge
charge.Calculator(m0).piElectron('mulliken')

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 2.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 3.    ,  0.2958,  0.4785,  0.8267,  0.7746],
       [ 4.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 5.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 6.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 7.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 8.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 9.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [10.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [11.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [12.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [13.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [14.    ,  0.9178,  0.2795,  0.2821,  1.7893],
       [15.    ,  0.9178,  0.2795,  0.2821,  0.5965],
       [16.    ,  0.9178,  0.2795,  0.2821,  1.5882],
       [17.    ,  0.9188,  0.2796,  0.2787,  1.8668],
       [18.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [19.    ,  0.    ,  0

In [3]:
from pywfn.atomprop import direction
direction.Calculator(m0).normal(3)

array([0.2958, 0.4785, 0.8267])