In [1]:
import sys
sys.path.append('d:/code/pywfn')
from pywfn.base import Mol
from pywfn.reader import LogReader
from pywfn.bondprop import order
import numpy as np

动态链接库目录 d:\code\pywfn\pywfn\libs
当前系统:windows


In [9]:
path=rf"D:\gfile\HFV\键级分解\CH3-CH3.log"
mol=Mol(LogReader(path))
mol.atom(1)._props['normal']=np.array([1.0,0.0,0.0])
mol.atom(5)._props['normal']=np.array([1.0,0.0,0.0])
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,5])

[[1.     2.     0.9563]
 [1.     3.     0.9563]
 [1.     4.     0.9563]
 [1.     5.     1.0267]
 [5.     6.     0.9563]
 [5.     7.     0.9563]
 [5.     8.     0.9563]]


[1.0197389800125438,
 0.14596545849554382,
 0.145885457470515,
 0.001855245979139272]

In [10]:
path=rf"D:\gfile\HFV\键级分解\CH2-CH2.log"
mol=Mol(LogReader(path))
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,4])

[[1.     2.     0.9423]
 [1.     3.     0.9423]
 [1.     4.     2.0419]
 [4.     5.     0.9423]
 [4.     6.     0.9423]]


[1.0400718470600043,
 1.000001178612489,
 0.21511697664393242,
 7.57596146196813e-31]

In [11]:
path=rf"D:\gfile\HFV\键级分解\CH-CH.log"
mol=Mol(LogReader(path))
mol.atom(1)._props['normal']=np.array([1.0,0.0,0.0])
mol.atom(3)._props['normal']=np.array([1.0,0.0,0.0])
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,3])

[[1.     2.     0.9225]
 [1.     3.     2.9704]
 [3.     4.     0.9225]]


[1.0387080667936879, 1.0000044591430988, 1.000004459143099, 0.0]

In [12]:
path=rf"D:\gfile\HFV\键级分解\O2.out"
mol=Mol(LogReader(path))
mol.atom(1)._props['normal']=np.array([1.0,0.0,0.0])
mol.atom(2)._props['normal']=np.array([1.0,0.0,0.0])
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,2])

[[1.     2.     1.8473]]


[0.9286136048332274, 0.0, 1.0000119543632446, 1.0135907539379123e-31]

In [13]:
path=rf"D:\gfile\HFV\键级分解\N2.out"
mol=Mol(LogReader(path))
mol.atom(1)._props['normal']=np.array([1.0,0.0,0.0])
mol.atom(2)._props['normal']=np.array([1.0,0.0,0.0])
print(mol.O_obts)
print(len(mol.O_obts))
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,2])

[0, 1, 2, 3, 4, 5, 6]
7
[[1.     2.     2.7463]]


[0.895358584223835,
 1.0000063112584894,
 1.0000063112584894,
 3.5560452730539346e-32]

In [14]:
path=rf"D:\gfile\HFV\键级分解\O2_T.log"
mol=Mol(LogReader(path))
mol.atom(1)._props['normal']=np.array([1.0,0.0,0.0])
mol.atom(2)._props['normal']=np.array([1.0,0.0,0.0])
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,2])

[[1.     2.     1.3738]]


[0.9297292573696352,
 0.5093784732212792,
 0.5093784732212792,
 1.8792557473654695e-31]

In [15]:
path=rf"D:\gfile\HFV\键级分解\N2_T.log"
mol=Mol(LogReader(path))
mol.atom(1)._props['normal']=np.array([1.0,0.0,0.0])
mol.atom(2)._props['normal']=np.array([1.0,0.0,0.0])
print(mol.O_obts)
print(len(mol.O_obts))
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,2])

[0, 1, 2, 3, 4, 5, 6, 7, 30, 31, 32, 33, 34, 35]
14
[[1.     2.     2.0025]]


[0.8978700875044311,
 0.9999412731531706,
 0.4854996275478908,
 1.1438816400687852e-32]

In [16]:
path=rf"D:\gfile\HFV\键级分解\CO.log"
mol=Mol(LogReader(path))
mol.atom(1)._props['normal']=np.array([1.0,0.0,0.0])
mol.atom(2)._props['normal']=np.array([1.0,0.0,0.0])
print(mol.O_obts)
print(len(mol.O_obts))
caler=order.Calculator(mol)
print(caler.mayer())
caler.decompose([1,2])

[0, 1, 2, 3, 4, 5, 6]
7
[[1.     2.     2.3867]]


[0.9452859787525766,
 0.8856775024218821,
 0.8856775024218819,
 5.977857903776852e-31]